/**
 * User API *  documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Injectable } from '@angular/core';
import { HttpEvent, HttpResponse } from '@angular/common/http';

import { Observable } from 'rxjs';


import { ApiResourceService } from './apiResourceService';
import { TikTokCommentRs } from '../model/tiktok/tiktokCommentRs';
import { TikTokScraperRq } from '../model/tiktok/tiktokScraperRq';


@Injectable({
  providedIn: 'root'
})
export class ScraperResourceService extends ApiResourceService {

    /**
     *
     *
     * @param observe set whether to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllTiktokComments(tiktokScraper: TikTokScraperRq, observe?: 'body', reportProgress?: boolean): Observable<TikTokCommentRs>;
    public getAllTiktokComments(tiktokScraper: TikTokScraperRq, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TikTokCommentRs>>;
    public getAllTiktokComments(tiktokScraper: TikTokScraperRq, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TikTokCommentRs>>;
    public getAllTiktokComments(tiktokScraper: TikTokScraperRq, observe: any = 'body', reportProgress?: boolean ): Observable<any> {

        let headers = this.defaultHeaders;
        return this.httpClient.request<TikTokCommentRs>('post',`${this.basePath}/api/tiktok-comments`,
            {
                body: tiktokScraper,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
