import { EnvironmentProviders, importProvidersFrom } from '@angular/core';
import {
  BellOutline,
  ClockCircleOutline,
  EditOutline,
  EyeOutline,
  FacebookFill,
  GooglePlusCircleFill,
  LogoutOutline,
  MinusOutline,
  PlusOutline,
  QuestionCircleOutline,
  SearchOutline,
  TikTokFill,
  UnorderedListOutline,
  UploadOutline,
  UpOutline,
  UserOutline,
  FileDoneOutline,
  UnderlineOutline,
  FilterOutline,
  MailTwoTone,
  LoginOutline,
  CopyOutline,
  SaveOutline,
  MenuFoldOutline,
  TeamOutline,
  MenuUnfoldOutline,
  MessageOutline,
  ShopOutline,
  SettingOutline,
  SendOutline,
  MergeCellsOutline,
  SplitCellsOutline,
  CameraOutline,
  VideoCameraOutline,
  PictureOutline,
  VideoCameraAddOutline,
} from '@ant-design/icons-angular/icons';
import { NzIconModule } from 'ng-zorro-antd/icon';


const icons = [
  CameraOutline,
  VideoCameraOutline,
  PictureOutline,
  VideoCameraAddOutline,
  MergeCellsOutline,
  SplitCellsOutline,
  SendOutline,
  SettingOutline,
  ShopOutline,
  MessageOutline,
  MenuUnfoldOutline,
  TeamOutline,
  MenuFoldOutline,
  FacebookFill,
  TikTokFill,
  PlusOutline,
  MinusOutline,
  ClockCircleOutline,
  QuestionCircleOutline,
  BellOutline,
  UpOutline,
  GooglePlusCircleFill,
  EyeOutline,
  EditOutline,
  UserOutline,
  UnorderedListOutline,
  UploadOutline,
  SearchOutline,
  LogoutOutline,
  FileDoneOutline,
  UnderlineOutline,
  FilterOutline,
  MailTwoTone,
  LoginOutline,
  CopyOutline,
  SaveOutline
];
export function provideNzIcons(): EnvironmentProviders {
  return importProvidersFrom(NzIconModule.forRoot(icons));
}
